// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMMi8ElskSNppyTAAk693NyTGE0Isdq_M',
    appId: '1:245630543692:web:17cc8c2306c4fa1d0f91e9',
    messagingSenderId: '245630543692',
    projectId: 'chat-app-ac0fd',
    authDomain: 'chat-app-ac0fd.firebaseapp.com',
    storageBucket: 'chat-app-ac0fd.firebasestorage.app',
    measurementId: 'G-CXSRTGNN7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKXLlNAj6tm3yE1GT89cWELWZouT08xqU',
    appId: '1:245630543692:android:f49755146060060b0f91e9',
    messagingSenderId: '245630543692',
    projectId: 'chat-app-ac0fd',
    storageBucket: 'chat-app-ac0fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0czm1YDiziknkuYv7vFv2Gi3SosFrt5k',
    appId: '1:245630543692:ios:f5c9f292bc1d4c110f91e9',
    messagingSenderId: '245630543692',
    projectId: 'chat-app-ac0fd',
    storageBucket: 'chat-app-ac0fd.firebasestorage.app',
    iosBundleId: 'com.example.chateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0czm1YDiziknkuYv7vFv2Gi3SosFrt5k',
    appId: '1:245630543692:ios:f5c9f292bc1d4c110f91e9',
    messagingSenderId: '245630543692',
    projectId: 'chat-app-ac0fd',
    storageBucket: 'chat-app-ac0fd.firebasestorage.app',
    iosBundleId: 'com.example.chateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMMi8ElskSNppyTAAk693NyTGE0Isdq_M',
    appId: '1:245630543692:web:31a0a38b0ff213f60f91e9',
    messagingSenderId: '245630543692',
    projectId: 'chat-app-ac0fd',
    authDomain: 'chat-app-ac0fd.firebaseapp.com',
    storageBucket: 'chat-app-ac0fd.firebasestorage.app',
    measurementId: 'G-D0Z6S545Z0',
  );

}